In [2]:
#import libraries
from dotenv import load_dotenv
from tradingview_ta import TA_Handler, Interval, Exchange
import datetime
import os
import logging
import pandas as pd
from pathlib import Path
%matplotlib inline

In [3]:
#Create TradingView variable and activate env variables
from tvDatafeed import TvDatafeed,Interval
load_dotenv()
tradev_id = os.getenv("username")
tradev_secret_key = os.getenv("password")

In [4]:
#Log into TradingView
logging.basicConfig(level=logging.DEBUG)
tv = TvDatafeed(tradev_id, tradev_secret_key, chromedriver_path=None)

DEBUG:tvDatafeed.main:auth loaded

In [6]:
#Get pricing history - simple method
litecoin_prices = tv.get_hist(symbol='LTCUSD',exchange='COINBASE',interval=Interval.in_daily,n_bars=500)
litecoin_prices

DEBUG:root:creating websocket connection
DEBUG:tvDatafeed.main:getting data for COINBASE:LTCUSD...

,symbol,open,high,low,close,volume
datetime,,,,,,
2020-05-03 19:00:00,COINBASE:LTCUSD,48.16,48.27,45.26,47.07,2.057719e+05
2020-05-04 19:00:00,COINBASE:LTCUSD,47.07,47.84,45.79,46.58,1.241177e+05
2020-05-05 19:00:00,COINBASE:LTCUSD,46.62,47.64,44.47,45.06,1.722932e+05
2020-05-06 19:00:00,COINBASE:LTCUSD,45.04,48.25,44.50,47.46,2.407533e+05
2020-05-07 19:00:00,COINBASE:LTCUSD,47.43,48.50,46.40,47.74,2.371929e+05
...,...,...,...,...,...,...
2021-09-10 19:00:00,COINBASE:LTCUSD,174.12,186.06,173.25,178.56,2.787188e+05
2021-09-11 19:00:00,COINBASE:LTCUSD,178.59,186.10,175.20,182.96,2.629131e+05
2021-09-12 19:00:00,COINBASE:LTCUSD,183.01,237.88,170.82,179.36,1.496173e+06
2021-09-13 19:00:00,COINBASE:LTCUSD,179.40,188.88,176.21,183.09,3.976001e+05
2021-09-14 19:00:00,COINBASE:LTCUSD,183.13,191.86,179.59,187.71,2.956546e+05